# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemouteSmartRieltor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19RemouteSmartRieltor.proto\x12\x07\x65xample\"\x18\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"\x14\n\x04\x46ile\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"&\n\x05Model\x12\x0f\n\x07idModel\x18\x01 \x01(\x05\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\"\x14\n\x04Stat\x12\x0c\n\x04stat\x18\x01 \x01(\x0c\"\x1a\n\x07Predict\x12\x0f\n\x07predict\x18\x01 \x01(\x0c\"4\n\x0cIntervalDate\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t2\xa7\x01\n\x0e\x45nginerService\x12\x30\n\tpostModel\x12\x0e.example.Model\x1a\x11.example.Response\"\x00\x12.\n\x08postStat\x12\r.example.Stat\x1a\x11.example.Response\"\x00\x12\x33\n\x07getData\x12\x15.example.IntervalDate\x1a\r.example.File\"\x00(\x01\x32p\n\rClientService\x12.\n\x08postData\x12\r.example.File\x1a\x11.example.Response\"\x00\x12/\n\ngetPredict\x12\r.example.File\x1a\x10.example.Predict\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemouteSmartRieltor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=38
  _RESPONSE._serialized_end=62
  _FILE._serialized_start=64
  _FILE._serialized_end=84
  _MODEL._serialized_start=86
  _MODEL._serialized_end=124
  _STAT._serialized_start=126
  _STAT._serialized_end=146
  _PREDICT._serialized_start=148
  _PREDICT._serialized_end=174
  _INTERVALDATE._serialized_start=176
  _INTERVALDATE._serialized_end=228
  _ENGINERSERVICE._serialized_start=231
  _ENGINERSERVICE._serialized_end=398
  _CLIENTSERVICE._serialized_start=400
  _CLIENTSERVICE._serialized_end=512
# @@protoc_insertion_point(module_scope)
