# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import RemouteSmartRieltor_pb2 as RemouteSmartRieltor__pb2


class EngineerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.postData = channel.stream_unary(
                '/example.EngineerService/postData',
                request_serializer=RemouteSmartRieltor__pb2.Data.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                )
        self.getData = channel.unary_stream(
                '/example.EngineerService/getData',
                request_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Data.FromString,
                )
        self.postStat = channel.unary_unary(
                '/example.EngineerService/postStat',
                request_serializer=RemouteSmartRieltor__pb2.Stat.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                )
        self.postTorchModel = channel.unary_unary(
                '/example.EngineerService/postTorchModel',
                request_serializer=RemouteSmartRieltor__pb2.TorchModel.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                )
        self.postCatBoostModel = channel.unary_unary(
                '/example.EngineerService/postCatBoostModel',
                request_serializer=RemouteSmartRieltor__pb2.CatBoostModel.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                )


class EngineerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def postData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def postStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def postTorchModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def postCatBoostModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'postData': grpc.stream_unary_rpc_method_handler(
                    servicer.postData,
                    request_deserializer=RemouteSmartRieltor__pb2.Data.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
            ),
            'getData': grpc.unary_stream_rpc_method_handler(
                    servicer.getData,
                    request_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Data.SerializeToString,
            ),
            'postStat': grpc.unary_unary_rpc_method_handler(
                    servicer.postStat,
                    request_deserializer=RemouteSmartRieltor__pb2.Stat.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
            ),
            'postTorchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.postTorchModel,
                    request_deserializer=RemouteSmartRieltor__pb2.TorchModel.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
            ),
            'postCatBoostModel': grpc.unary_unary_rpc_method_handler(
                    servicer.postCatBoostModel,
                    request_deserializer=RemouteSmartRieltor__pb2.CatBoostModel.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.EngineerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EngineerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def postData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/example.EngineerService/postData',
            RemouteSmartRieltor__pb2.Data.SerializeToString,
            RemouteSmartRieltor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/example.EngineerService/getData',
            RemouteSmartRieltor__pb2.Response.SerializeToString,
            RemouteSmartRieltor__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def postStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.EngineerService/postStat',
            RemouteSmartRieltor__pb2.Stat.SerializeToString,
            RemouteSmartRieltor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def postTorchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.EngineerService/postTorchModel',
            RemouteSmartRieltor__pb2.TorchModel.SerializeToString,
            RemouteSmartRieltor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def postCatBoostModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.EngineerService/postCatBoostModel',
            RemouteSmartRieltor__pb2.CatBoostModel.SerializeToString,
            RemouteSmartRieltor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.postData = channel.stream_unary(
                '/example.ClientService/postData',
                request_serializer=RemouteSmartRieltor__pb2.Data.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.Response.FromString,
                )
        self.getPredict = channel.stream_stream(
                '/example.ClientService/getPredict',
                request_serializer=RemouteSmartRieltor__pb2.Booking.SerializeToString,
                response_deserializer=RemouteSmartRieltor__pb2.StateBooking.FromString,
                )


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def postData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPredict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'postData': grpc.stream_unary_rpc_method_handler(
                    servicer.postData,
                    request_deserializer=RemouteSmartRieltor__pb2.Data.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.Response.SerializeToString,
            ),
            'getPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.getPredict,
                    request_deserializer=RemouteSmartRieltor__pb2.Booking.FromString,
                    response_serializer=RemouteSmartRieltor__pb2.StateBooking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def postData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/example.ClientService/postData',
            RemouteSmartRieltor__pb2.Data.SerializeToString,
            RemouteSmartRieltor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/example.ClientService/getPredict',
            RemouteSmartRieltor__pb2.Booking.SerializeToString,
            RemouteSmartRieltor__pb2.StateBooking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
